"""Response envelopes for the SBS SupTech API.

:class:`ProblemDetail` is the RFC 9457 error envelope used by every non-2xx
response. Other classes are the success-side envelopes.
"""

from __future__ import annotations

from datetime import date, datetime
from typing import Literal

from pydantic import AnyUrl, BaseModel, ConfigDict, Field

from sbs_api.models.anexo_1a import (
    Channel,
    Complaint,
    MotivoCode,
    ProductCategory,
    ResolutionStatus,
    Severity,
)


# ---------------------------------------------------------------------------
# RFC 9457 problem+json
# ---------------------------------------------------------------------------


class ProblemDetail(BaseModel):
    """RFC 9457 Problem Details for HTTP APIs.

    Every non-2xx response carries this envelope under content type
    ``application/problem+json``. The ``type`` URI namespace is a placeholder
    pending SBS sign-off; see docs/sessions/2026-05-18-prompt-05-open-questions.md.
    """

    model_config = ConfigDict(
        extra="forbid",
        json_schema_extra={
            "examples": [
                {
                    "type": "https://sbs.gob.pe/errors/SBS-400-001",
                    "title": "Validation failed",
                    "status": 422,
                    "detail": (
                        "complaint.complainant_district must match pattern "
                        "'^\\d{4}$' (received: 'XYZ')."
                    ),
                    "instance": "/v1/complaints",
                    "code": "SBS-400-001",
                    "trace_id": "00-7b91f5a2c0b14e9d8c44a5f0c70d8b39-1f3a4ee9c84a4d27-01",
                    "errors": [
                        {
                            "field": "complaint.complainant_district",
                            "rule": "pattern",
                            "message": "value 'XYZ' does not match INEI ubigeo pattern",
                        }
                    ],
                }
            ]
        },
    )

    type: AnyUrl = Field(
        ...,
        description=(
            "RFC 9457 'type' — a URI identifying the problem class. SBS uses "
            "the placeholder namespace https://sbs.gob.pe/errors/{code} until "
            "the namespace is confirmed."
        ),
    )
    title: str = Field(
        ...,
        min_length=3,
        max_length=200,
        description="Short, human-readable summary of the problem class.",
    )
    status: int = Field(
        ...,
        ge=400,
        le=599,
        description="The HTTP status code originally generated by the origin server.",
    )
    detail: str | None = Field(
        default=None,
        max_length=2000,
        description=(
            "Human-readable explanation specific to this occurrence. Plain "
            "Spanish or English."
        ),
    )
    instance: str | None = Field(
        default=None,
        description="URI reference identifying the specific occurrence.",
    )
    code: str = Field(
        ...,
        pattern=r"^SBS-\d{3}-\d{3}$",
        description=(
            "Stable machine-readable error code. The error catalog at "
            "api/openapi/error-catalog.md is the canonical list."
        ),
    )
    trace_id: str | None = Field(
        default=None,
        description=(
            "W3C traceparent identifier of the request, propagated from "
            "OpenTelemetry. Institutions echo this in support requests."
        ),
    )
    errors: list["ProblemFieldError"] | None = Field(
        default=None,
        description=(
            "When the problem is a validation failure across multiple fields, "
            "each individual field error is enumerated here. Omitted for "
            "single-field or non-validation problems."
        ),
    )


class ProblemFieldError(BaseModel):
    """Single field-level error inside a :class:`ProblemDetail`."""

    model_config = ConfigDict(extra="forbid")

    field: str = Field(
        ...,
        min_length=1,
        max_length=200,
        description="JSON path of the offending field (e.g., complaint.complainant_district).",
    )
    rule: str = Field(
        ...,
        min_length=1,
        max_length=64,
        description="Validation rule that failed (e.g., 'pattern', 'min_length').",
    )
    message: str = Field(
        ...,
        min_length=1,
        max_length=500,
        description="Human-readable message describing the rule violation.",
    )


# ---------------------------------------------------------------------------
# Complaint responses
# ---------------------------------------------------------------------------


class ComplaintCreated(BaseModel):
    """Body of the 201 response from ``POST /v1/complaints``."""

    model_config = ConfigDict(extra="forbid")

    complaint_id: str = Field(
        ...,
        description="The complaint_id from the submitted payload, echoed for confirmation.",
    )
    institution_id: str = Field(
        ...,
        description="The institution_id from the submitted payload.",
    )
    received_at: datetime = Field(
        ...,
        description=(
            "Server-assigned receipt timestamp (UTC). Distinct from the "
            "Anexo 1-A 'received_date' which is the institution-recorded "
            "date the user submitted the complaint."
        ),
    )
    resolution_status: ResolutionStatus = Field(
        ...,
        description="The resolution_status as accepted by the server.",
    )
    client_submission_id: str | None = Field(
        default=None,
        description="Echo of the optional client_submission_id from the request.",
    )


class SupervisoryMetadata(BaseModel):
    """SBS-derived fields populated by the Triage agent — never by the FI.

    Response-side only (P-RESHAPE-9 / standards pack v0.2.0). This block
    is excluded from the FI submission contract (:class:`Complaint` stays
    27 fields, ``extra=forbid``); it gives ``system_signal`` a clean home
    on the list view without touching Annex 1-A.
    """

    model_config = ConfigDict(extra="forbid")

    system_signal: bool | None = Field(
        default=None,
        description=(
            "True if Triage detected a system-level signal (outage, fraud, "
            "breach indicator)."
        ),
    )
    system_signal_reasons: list[
        Literal[
            "OUTAGE_KEYWORD",
            "FRAUD_KEYWORD",
            "AMOUNT_THRESHOLD",
            "REGULATORY_BREACH_INDICATOR",
        ]
    ] | None = Field(default=None)
    validation_verdict: Literal[
        "VALID", "RECOVERABLE", "INSUFFICIENT", "INVALID"
    ] | None = Field(default=None)
    triage_classified_at: datetime | None = Field(default=None)


class ComplaintListItem(BaseModel):
    """One row of ``GET /v1/complaints`` list response.

    A reduced view of the full :class:`Complaint` payload. Free-text fields
    (description_text) are omitted from list responses to keep payloads small;
    institutions fetch the full :class:`Complaint` via the by-id endpoint.
    """

    model_config = ConfigDict(extra="forbid")

    complaint_id: str
    institution_id: str
    received_date: date
    product_category: ProductCategory
    channel: Channel
    motivo_code: MotivoCode
    severity: Severity
    resolution_status: ResolutionStatus
    received_at: datetime
    supervisory_metadata: SupervisoryMetadata | None = Field(
        default=None,
        description=(
            "SBS-side fields populated by Triage. Read-only for FIs; excluded "
            "from FI submission validation."
        ),
    )


class ComplaintListResponse(BaseModel):
    """Body of ``GET /v1/complaints`` (collection)."""

    model_config = ConfigDict(extra="forbid")

    items: list[ComplaintListItem]
    next_cursor: str | None = Field(
        default=None,
        description=(
            "Opaque cursor. If null, there are no more pages. Pass back as "
            "the next_cursor query parameter to fetch the next page."
        ),
    )


# ---------------------------------------------------------------------------
# Batch responses
# ---------------------------------------------------------------------------


class BatchSubmission(BaseModel):
    """202 response from ``POST /v1/batches`` (multipart upload accepted).

    The Location header on the 202 carries the URL of the status endpoint;
    the body is intentionally minimal — just the batch_id and the initial
    state. The institution polls the status endpoint or waits for the
    outbound webhook callback (ADR 0035) on completion.
    """

    model_config = ConfigDict(extra="forbid")

    batch_id: str = Field(
        ...,
        pattern=r"^batch_[A-Za-z0-9]{16,32}$",
        description="Server-assigned batch identifier.",
    )
    status: Literal["pending"] = Field(
        ...,
        description=(
            "Initial state. The batch has been persisted and queued; the "
            "worker transitions it to `processing` and then `complete` or "
            "`failed`."
        ),
    )


class BatchStatus(BaseModel):
    """Body of ``GET /v1/batches/{batch_id}``."""

    model_config = ConfigDict(extra="forbid")

    batch_id: str = Field(..., pattern=r"^batch_[A-Za-z0-9]{16,32}$")
    institution_id: str = Field(..., pattern=r"^SBS-\d{4,6}$")
    status: Literal[
        "pending",
        "processing",
        "complete",
        "failed",
    ] = Field(
        ...,
        description=(
            "Lifecycle state. ADR 0034 §state-machine: pending → processing "
            "→ complete | failed. Once terminal, the state does not change."
        ),
    )
    submitted_at: datetime
    completed_at: datetime | None = None
    row_count_submitted: int = Field(..., ge=0)
    row_count_accepted: int = Field(..., ge=0)
    row_count_rejected: int = Field(..., ge=0)
    failure_reason: str | None = Field(
        default=None,
        description=(
            "Set when status is 'failed'. Short human-readable message; "
            "details (e.g. exception type, stack) live in the structlog "
            "stream, not in the API response."
        ),
    )


class BatchRowRejectionDetail(BaseModel):
    """One row of ``GET /v1/batches/{batch_id}/rejections`` (Workstream C).

    Per-row outcome for the *failed* rows of a batch. Accepted rows are
    not enumerated here — they appear in the Tier 1 GET /v1/complaints
    listing once persisted by the worker. Rejection envelope mirrors the
    :class:`ProblemFieldError` shape so SDK error handlers can reuse one
    code path for Tier 1 and Tier 2 field errors.
    """

    model_config = ConfigDict(extra="forbid")

    row_index: int = Field(
        ...,
        ge=0,
        description="Zero-indexed row position in the source CSV.",
    )
    field: str | None = Field(
        default=None,
        max_length=200,
        description="JSON-path of the offending field; null when multi-field.",
    )
    rule: str = Field(
        ...,
        min_length=1,
        max_length=64,
        description="Validation rule that failed (e.g. 'pattern', 'min_length').",
    )
    message: str = Field(
        ...,
        min_length=1,
        max_length=2000,
        description="Human-readable message describing the rule violation.",
    )


class BatchRejectionsResponse(BaseModel):
    """Body of ``GET /v1/batches/{batch_id}/rejections`` (Workstream C)."""

    model_config = ConfigDict(extra="forbid")

    batch_id: str = Field(..., pattern=r"^batch_[A-Za-z0-9]{16,32}$")
    rejections: list[BatchRowRejectionDetail]
    next_cursor: str | None = None


# ---------------------------------------------------------------------------
# Institution status
# ---------------------------------------------------------------------------


class InstitutionStatus(BaseModel):
    """Body of ``GET /v1/institutions/{institution_id}/status``."""

    model_config = ConfigDict(extra="forbid")

    institution_id: str = Field(..., pattern=r"^SBS-\d{4,6}$")
    onboarded: bool = Field(
        ...,
        description="True if the institution is active in the sandbox.",
    )
    rate_limit_per_minute: int = Field(
        ...,
        ge=0,
        description="Per-minute Tier 1 ingestion rate limit allocated to this institution.",
    )
    complaints_received_today: int = Field(
        ...,
        ge=0,
        description="Count of Tier 1 + Tier 2 complaints received in the current UTC day.",
    )
    last_submission_at: datetime | None = Field(
        default=None,
        description="Timestamp of the institution's most recent submission. Null if none.",
    )
    schema_version: str = Field(
        ...,
        pattern=r"^v\d+\.\d+\.\d+$",
        description="Anexo 1-A schema version the institution is currently aligned to.",
    )


# ---------------------------------------------------------------------------
# Health and metadata
# ---------------------------------------------------------------------------


class HealthStatus(BaseModel):
    """Body of ``GET /v1/health``."""

    model_config = ConfigDict(extra="forbid")

    status: Literal["ok", "degraded", "down"] = Field(
        ...,
        description=(
            "Aggregate liveness. 'ok' means all dependencies reachable; "
            "'degraded' means some dependencies are unreachable but the API "
            "can still serve reads; 'down' means a critical dependency is "
            "unreachable."
        ),
    )
    version: str = Field(
        ...,
        description="Build version of the running API service.",
        examples=["0.1.0"],
    )
    checked_at: datetime = Field(
        ...,
        description="Timestamp of the health probe.",
    )


class VersionInfo(BaseModel):
    """Body of ``GET /v1/version``."""

    model_config = ConfigDict(extra="forbid")

    api_version: str = Field(
        ...,
        description="OpenAPI info.version of the contract this service implements.",
        examples=["0.1.0"],
    )
    build_sha: str = Field(
        ...,
        min_length=7,
        max_length=40,
        description="Git commit SHA of the build.",
    )
    schema_version: str = Field(
        ...,
        pattern=r"^v\d+\.\d+\.\d+$",
        description="Active Anexo 1-A schema version.",
    )


# Resolve forward references inside ProblemDetail.errors
ProblemDetail.model_rebuild()


__all__ = [
    "BatchRejectionsResponse",
    "BatchRowRejectionDetail",
    "BatchStatus",
    "BatchSubmission",
    "ComplaintCreated",
    "ComplaintListItem",
    "ComplaintListResponse",
    "HealthStatus",
    "InstitutionStatus",
    "ProblemDetail",
    "ProblemFieldError",
    "VersionInfo",
]
