#!/usr/bin/env bash
# Generate a sandbox dev CA + two leaf client certs for mTLS testing.
#
# Outputs (all under dev-ca/, gitignored):
#   ca.key                       — root CA private key (RSA 4096)
#   ca.pem                       — self-signed root CA cert (10-year validity)
#   banco-demo-001-key.pem       — leaf private key (RSA 2048)
#   banco-demo-001.pem           — leaf cert signed by ca.pem (1-year validity)
#   coopac-demo-002-key.pem      — leaf private key
#   coopac-demo-002.pem          — leaf cert
#   thumbprints.txt              — `<institution_id>\t<cn>\t<sha256-hex>` per leaf
#   seed-certificates.sql        — INSERT statements consumed by dev-up.sh
#
# Idempotent: re-runs do not regenerate unless --force is passed.
#
# Usage:
#   bash scripts/dev-ca.sh           # generate if missing
#   bash scripts/dev-ca.sh --force   # regenerate from scratch
#
# Exit codes:
#   0  ok
#   1  openssl missing or unusable
#   2  unexpected error during generation

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")"/.. && pwd)"
cd "$REPO_ROOT"

FORCE=0
if [[ "${1:-}" == "--force" ]]; then
  FORCE=1
fi

CA_DIR="dev-ca"
CA_KEY="$CA_DIR/ca.key"
CA_CERT="$CA_DIR/ca.pem"
THUMBS="$CA_DIR/thumbprints.txt"
SEED_SQL="$CA_DIR/seed-certificates.sql"

if ! command -v openssl >/dev/null 2>&1; then
  echo "ERROR: openssl not found on PATH" >&2
  exit 1
fi

mkdir -p "$CA_DIR"

# --- Root CA -----------------------------------------------------------------

if [[ -f "$CA_CERT" && -f "$CA_KEY" && $FORCE -eq 0 ]]; then
  echo "==> dev CA already present at $CA_CERT (use --force to regenerate)"
else
  echo "==> generating root CA"
  openssl genrsa -out "$CA_KEY" 4096 2>/dev/null
  openssl req -new -x509 -sha256 -days 3650 \
    -key "$CA_KEY" \
    -out "$CA_CERT" \
    -subj "/C=PE/O=SBS Sandbox/CN=SBS Sandbox CA" 2>/dev/null
  echo "    wrote $CA_CERT"
fi

# --- Leaf cert helper --------------------------------------------------------

issue_leaf () {
  local cn="$1"
  local eku="${2:-clientAuth}"   # clientAuth (institutions) or serverAuth (uvicorn)
  local subj_o="${3:-SBS Sandbox Institutions}"
  local san_line="${4:-}"
  # Portable lowercase + underscore→dash (macOS ships bash 3.2; no ${var,,})
  local stem
  stem="$(printf '%s' "$cn" | tr '[:upper:]_' '[:lower:]-')"
  local key="$CA_DIR/${stem}-key.pem"
  local cert="$CA_DIR/${stem}.pem"
  local csr="$CA_DIR/.${stem}.csr"

  if [[ -f "$cert" && -f "$key" && $FORCE -eq 0 ]]; then
    echo "==> leaf cert for $cn already present (use --force to regenerate)"
    return 0
  fi

  echo "==> issuing leaf cert for CN=$cn (EKU=$eku)"
  openssl genrsa -out "$key" 2048 2>/dev/null
  openssl req -new -sha256 \
    -key "$key" \
    -out "$csr" \
    -subj "/C=PE/O=${subj_o}/CN=${cn}" 2>/dev/null
  openssl x509 -req -sha256 \
    -in "$csr" \
    -CA "$CA_CERT" -CAkey "$CA_KEY" -CAcreateserial \
    -out "$cert" \
    -days 365 \
    -extfile <(printf 'extendedKeyUsage = %s\nbasicConstraints = critical, CA:false\n%s' "$eku" "$san_line") \
    2>/dev/null
  rm -f "$csr"
  echo "    wrote $cert"
}

issue_leaf "BANCO_DEMO_001"  "clientAuth"
issue_leaf "COOPAC_DEMO_002" "clientAuth"
# Sandbox server cert (serverAuth EKU; SAN covers localhost and the
# sandbox host name). Used by scripts/run-api.sh and the mTLS
# integration test as uvicorn's TLS identity.
issue_leaf \
  "sbs-suptech-sandbox.local" \
  "serverAuth" \
  "SBS Sandbox Server" \
  "subjectAltName = DNS:sbs-suptech-sandbox.local,DNS:localhost,IP:127.0.0.1\n"

# --- Thumbprints + seed SQL --------------------------------------------------
#
# The sandbox seed maps:
#   CN=BANCO_DEMO_001  → institution_id SBS-001234
#   CN=COOPAC_DEMO_002 → institution_id SBS-005678

leaf_thumbprint () {
  local cert="$1"
  # LibreSSL `x509 -fingerprint -sha256` prints "SHA256 Fingerprint=AA:BB:..."
  openssl x509 -in "$cert" -noout -fingerprint -sha256 \
    | sed -E 's/^.*=//' | tr -d ':' | tr 'A-Z' 'a-z'
}

BANCO_CERT="$CA_DIR/banco-demo-001.pem"
COOPAC_CERT="$CA_DIR/coopac-demo-002.pem"

BANCO_TP="$(leaf_thumbprint "$BANCO_CERT")"
COOPAC_TP="$(leaf_thumbprint "$COOPAC_CERT")"

cat > "$THUMBS" <<EOF
# institution_id    CN                  SHA-256(DER) thumbprint
SBS-001234	BANCO_DEMO_001	$BANCO_TP
SBS-005678	COOPAC_DEMO_002	$COOPAC_TP
EOF

cat > "$SEED_SQL" <<EOF
-- Generated by scripts/dev-ca.sh. Inserts the dev-CA leaf certs into
-- institution_certificates so the mTLS dependency can resolve them at
-- request time. Re-running is safe: ON CONFLICT DO NOTHING.

INSERT INTO institution_certificates (
    institution_id, cn, sha256_thumbprint,
    not_before, not_after, revoked_at, created_at
) VALUES
    ('SBS-001234', 'BANCO_DEMO_001',  '$BANCO_TP',  now() - interval '1 day', now() + interval '365 days', NULL, now()),
    ('SBS-005678', 'COOPAC_DEMO_002', '$COOPAC_TP', now() - interval '1 day', now() + interval '365 days', NULL, now())
ON CONFLICT (sha256_thumbprint) DO NOTHING;
EOF

echo
echo "==> dev CA ready"
echo "    $THUMBS"
echo "    $SEED_SQL"
echo
echo "Next: bash scripts/dev-up.sh   (applies the seed if dev-ca/seed-certificates.sql is present)"
