# SPDX-License-Identifier: Apache-2.0
"""Egress audit for cloud inference calls.

Revision ID: 20260817_0001
Revises: 20260810_0001
Create Date: 2026-08-17

``cloud`` is the only model provider that sends complaint content to
infrastructure the supervisory authority does not operate. Until now nothing in
the database recorded that it had happened: the provider logged a line to
stderr, and ``agent_runs.model_provider`` recorded *that* a cloud model served a
run but nothing about what left the process or whether it was redacted first.

This table closes that. One row per outbound cloud call, written before the
request goes on the wire — the audited event is the egress, not its success, so
a call that times out still leaves a record that the payload was sent.

**It stores no text.** Not the raw narrative and not the redacted one: a column
holding the redacted prompt would be a second copy of the complaint living in an
audit table, and one holding the raw prompt would defeat the purpose. Counts by
entity kind are recorded instead — enough to evidence that redaction ran and
what it found, useless as a source of personal data. Same discipline as
``validation_audit``.

Hand-written rather than autogenerated. Additive and reversible: one new table
and its two indexes, **no DROP, ALTER or data change of any kind against
existing objects**, so applying it to a live database cannot affect anything
already there. Autogenerate was deliberately not used because it emits four
spurious ``op.drop_index`` lines on this schema (see HANDOVER-NOTES.md under
"Database and migrations").
"""

from __future__ import annotations

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260817_0001"
down_revision: str | None = "20260810_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "cloud_inference_audit",
        sa.Column("id", sa.String(length=36), nullable=False),
        # No foreign key to complaints: an egress audit must not be capable of
        # failing on a referential problem elsewhere, and the boot
        # healthcheck's canary call belongs to no complaint.
        sa.Column("complaint_id", sa.String(length=32), nullable=True),
        sa.Column("agent_name", sa.String(length=64), nullable=True),
        # The Azure deployment addressed, recorded at request time.
        sa.Column("model_id", sa.String(length=128), nullable=False),
        # The assertion under audit.
        sa.Column("redaction_applied", sa.Boolean(), nullable=False),
        # {kind: count} — counts only, never values and never text.
        sa.Column(
            "entity_counts",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="{}",
        ),
        sa.Column("message_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("redacted_chars", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # "What went to the cloud for this complaint?"
    op.create_index(
        "ix_cloud_inference_audit_complaint_id_created_at",
        "cloud_inference_audit",
        ["complaint_id", "created_at"],
    )
    # "Was anything ever sent unredacted?" — the compliance sweep.
    op.create_index(
        "ix_cloud_inference_audit_redaction_applied",
        "cloud_inference_audit",
        ["redaction_applied"],
    )


def downgrade() -> None:
    # The only DROPs in this migration are here, undoing what upgrade() added
    # and nothing else.
    op.drop_index(
        "ix_cloud_inference_audit_redaction_applied",
        table_name="cloud_inference_audit",
    )
    op.drop_index(
        "ix_cloud_inference_audit_complaint_id_created_at",
        table_name="cloud_inference_audit",
    )
    op.drop_table("cloud_inference_audit")
